### ISSUE TITLE
Multi-Macro is moving the wrong key index to what is selected (Hard to contact you about this)

### ISSUE THREAD

**Issue by TheSouthernSanta** [SuchByte/Macro-Deck#1]
Hey, first of all. Love the software. But i'm trying to setup a multi-key macro, but i need to move some keys in between shift up and down, but those keys I try to move keep bringing the other keys of the same type down from earlier in the macro. I would love if this gets patched. Loving the use of .NET 👍

**Comment by TheSouthernSanta** [comment]
Here's a gif of what I mean.
![249588bab2432fbf17094833be26545a](https://user-images.githubusercontent.com/11086992/57976387-b2e7cd00-7a32-11e9-9692-be69d89ba12f.gif)

**Comment by SuchByte** [comment]
Will be fixed in Macro Deck 2. Thank you!
