### ISSUE TITLE
Discord Plugin Update

### ISSUE THREAD

**Issue by RecklessBoon** [SuchByte/Macro-Deck#105]
** Name of the plugin **
Discord Plugin

** GitHub repository **
https://github.com/RecklessBoon/Macro-Deck-Discord-Plugin

** Dependencies **
**NO CHANGES TO DEPENDENCIES**

_Existing Dependencies Below:_
Macro Deck version: 2.6.3.213560153
Discord.Net version: 2.4.0 [NuGet](https://www.nuget.org/packages/Discord.Net/)
DiscordRichPresence version: 1.0.175 [NuGet](https://www.nuget.org/packages/DiscordRichPresence/)
Newtonsoft.Json version: 12.0.2 [NuGet](https://www.nuget.org/packages/Newtonsoft.Json/)

This change is to address token swap failure crashing entire application.

**Comment by SuchByte** [comment]
Please also update the version in your project file (RecklessBoon.MacroDeck.Discord.csproj) in the future releases. For this update I did it myself.
