### ISSUE TITLE
This app is abandoned

### ISSUE THREAD

**Issue by rjdza** [SuchByte/Macro-Deck#11]
This app is abandoned - no way to contact the author about critical bugs. Don't bother logging tickets.

**Comment by rjdza** [comment]
This app is abandoned - no way to contact the author about critical bugs.  Don't bother logging tickets.

**Comment by rhystedstone** [comment]
I don't think it's abandoned. Literally a day after you posting that, a poll was posted on strawpoll.me, linked by the news page. The page's css is a bit messed up - as if he quickly added it. I think he may just be really busy, whether he's working on v2/v1.3.2 (Non pre-release) or not.
I'm really looking forward to v2 - This is probably the best "macro/control panel" software out there.
https://macrodeck.org/news/
https://www.strawpoll.me/20004854

**Comment by rhystedstone** [comment]
> I don't think it's abandoned. Literally a day after you posting that, a poll was posted on strawpoll.me, linked by the news page. The page's css is a bit messed up - as if he quickly added it. I think he may just be really busy, whether he's working on v2/v1.3.2 (Non pre-release) or not.
> I'm really looking forward to v2 - This is probably the best "macro/control panel" software out there.
> https://macrodeck.org/news/
> https://www.strawpoll.me/20004854

It's been 8 months and... nothing. The website is more broken. Yeah, it's abandoned.

**Comment by Shiro-Nek0** [comment]
apparently it's not :D , there is a new post from 4 days ago with the caption "in development": https://macrodeck.org/news/

**Comment by SuchByte** [comment]
I had a really busy time with absolutely no motivation but now I'm here again, making really good progress on Macro Deck 2!
