### ISSUE TITLE
When i start Macro Deck on PC, my "S" Key stop working.

### ISSUE THREAD

**Issue by FKTYDaniel** [SuchByte/Macro-Deck#113]
**Describe the bug**
As i said in the title. I have the latest version of your software and i'm using Windows 11. Hopefully

**Comment by SuchByte** [comment]
If you're using version 2.6.4, it's not a bug. You have set the "S" key as a hotkey on some button.

**Comment by FKTYDaniel** [comment]
Mr. @SuchByte, i think you didn't understood my problem. When i start Macro Deck, my 'S' key just doesn't work anymore unless i quit your software. I just can't write the letter 'S' in any notepad, browser, Macro Deck or other window in my PC. That is not normal at all, and your "solution" is not what i'm searching for solving this problem.

Words like:
Word**s** become -> Word
under**s**tood become -> undertood

because my 'S' key just doesn't work with your software open. **Did I make myself understood now?**

**Comment by SuchByte** [comment]
Well that's strange. Please pack the entire Macro Deck folder (%Appdata%\Macro Deck) into a zip archive and send it as email to suchbyte@gmail.com.

**Comment by FKTYDaniel** [comment]
@SuchByte ok, i will do that. As i have this issue, i will use the last version before 2.6.4 **(2.6.0)** to have an experience less problematic with my 'S' key.

**Comment by FKTYDaniel** [comment]
@SuchByte because of gmail security policy, i can't send you an email with the zip file. So i let it here

[Macro Deck.zip](https://github.com/SuchByte/Macro-Deck/files/7842304/Macro.Deck.zip)
.

**Comment by SuchByte** [comment]
Well I didn't noticed anyting that could cause this behaviour in your files and in the code. I just released a new dev version (2.6.5), can you please update to this version and if this bug happens again, please upload the log file (located in %Appdata%\Macro Deck\logs) here.

**Comment by FKTYDaniel** [comment]
@SuchByte i think it is fixed. I just downloaded the new version and it is all fine with me. Thank you for your good work. <3
