### ISSUE TITLE
Write Text Problem Since Update to 2.6.5.220121802

### ISSUE THREAD

**Issue by keithrawlinson** [SuchByte/Macro-Deck#121]
**Describe the bug**
Windows Utils Write Text (several issues) . There is so much wrong with Write Text since update it is difficult to describe.

**To Reproduce**
1. Create a new folder
2. Double-click on a button to create a new one 
3. Add a button title (E.G Call it '1')
4. Click on '+' then 'Action'
5. Click on 'Windows Utils'
6. Click on 'Write text'
7. If 'Write text' has previously been added to a button it will be shown in the 'Write text' box. If not then add a new Windows Utils Write Text. Add text as '1' (without ')
8. Click 'Save' and 'OK'
9. Double-click on another button in the same folder and call it '2'
10.  Click on '+' then 'Action'
11. Click on 'Windows Utils'
12. Click on 'Write text'
13. The text box will appear with '1' in it
14. Change text to '2'
15. Click 'Save' and 'OK'
16. Double-click on button 1.
17. You will see the Windows Utils Write text has changed to '2'

**Expected behavior**
Each new button should be clear then saved and then the variables should be nulled. It worked in the previous version, 2.6.4.... Only since the plugins reconfig has it stopped working correctly

**Screenshots**

![Bug](https://user-images.githubusercontent.com/84747729/149413167-ad82e100-f7b0-4a72-9b42-68187e267960.png)

**Comment by SuchByte** [comment]
This bug is already fixed in version 2.6.7-dev which can be downloaded.
