### ISSUE TITLE
Soundboard update

### ISSUE THREAD

**Issue by PhoenixWyllow** [SuchByte/Macro-Deck#123]
** Name of the plugin **
Soundboard4Macrodeck

** Version **
0.4.2

** GitHub repository **
https://github.com/PhoenixWyllow/Soundboard4MacroDeck2

** Dependencies **
Macro Deck version:
2.6.7+
[Soundboard4MacroDeck_0.4.22015.2238.zip](https://github.com/SuchByte/Macro-Deck/files/7876025/Soundboard4MacroDeck_0.4.22015.2238.zip)

**Comment by SuchByte** [comment]
For the future, it will be cool if you name the file like "soundboard4macrodeck-0.4.2.zip" instead of "Soundboard4MacroDeck_0.4.22015.2238.zip", thanks :)
