### ISSUE TITLE
Simple blue - Icon pack submission

### ISSUE THREAD

**Issue by imohammedramadan** [SuchByte/Macro-Deck#125]
**Name of the icon pack**
Simple blue

**Version**
1.0.0

**Author of the icon pack**
MidoMatrix

**Description of the icon pack**
A simple pack of blue icons, has media controls, on/off states for some and general use on/off switches.

**Icon pack file**
[simple-blue-1.0.0.iconpack.zip](https://github.com/SuchByte/Macro-Deck/files/7897351/simple-blue-1.0.0.iconpack.zip)

**Comment by SuchByte** [comment]
Hi, have you created the icons yourself?

**Comment by imohammedramadan** [comment]
yep, aside from the discord logo in the discord icons for mute and deafen, i created them all myself
