### ISSUE TITLE
On Press & On Release Quick-Tap Bug

### ISSUE THREAD

**Issue by keithrawlinson** [SuchByte/Macro-Deck#139]
**Describe the bug**
I thought I had raised this before but cannot find it so re-presenting it. Create text in 'On Press' and text in 'On Release'.  A short tap on a button shows the two texts but a quick tap and release shows a corrupted result (in a text editor such as Notepad)

**To Reproduce**
1. Go to 'a new button in any folder'
2. Double Click on 'button' and add any button label such as 'Tap Test'
3. Click on '+' and then 'Action' then 'Windows Utils' then 'write text'
4. Add the text 'On press test '
5. Click on 'OK'.
6. Click on 'On release' and repaet step 3 to 5 but entering the text 'On release' in step 4.
7. Click 'Save' and then 'OK'
8. Run a text editor.
9. On a client, quickly tap on and release the 'Tap Test' button.
10. Something like 'On prreelesass et estte st' is typed. See attached.

**Expected behavior**
'On press test On release test ' should be typed out

**Screenshots**
![Button Tap Examples](https://user-images.githubusercontent.com/84747729/151708950-ca25ae8b-2a68-40cd-a751-3935ef7da297.png)

**Additional context**
Sorry if you did see this before but as it wasn't resolved in 2.8.0 release and I couldn't find it in the list of 'Bugs' I felt I ought to flag it up again.

**Comment by SuchByte** [comment]
This has nothing to do with Macro Deck. I already moved your previous issue to the repo of the Windows Utils plugin and closed it with an explanation of why this is happening.

https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin/issues/13
