### ISSUE TITLE
Request for Macro Deck 2 v2.7.1

### ISSUE THREAD

**Issue by EugeneBadger** [SuchByte/Macro-Deck#146]
Hi guys, please tell me where you can download Macro Deck 2 v2.7.1 I will be very grateful. Macro Deck 2 v2.8.1 does not work correctly on Windows 8.1

**Comment by SuchByte** [comment]
Do you mean this issue: https://github.com/SuchByte/Macro-Deck/issues/145 ?

**Comment by EugeneBadger** [comment]
yes, problem https://github.com/SuchByte/Macro-Deck/issues/145

**Comment by SuchByte** [comment]
https://macrodeck.org/files/installer/macro-deck-2.7.1-dev.msi

I'll let you know when the bug is fixed and it is safe to update again.
