### ISSUE TITLE
Weird behavior using 'Open Website' 

### ISSUE THREAD

**Issue by iaxx** [SuchByte/Macro-Deck#16]
Can we please have a raw input option for 'open website' adding the `http://` yourself creates many weird issues if you try top open something that's not http.

**Comment by cywpierre** [comment]
> Can we please have a raw input option for 'open website' adding the `http://` yourself creates many weird issues if you try top open something that's not http.

I faced this issue too, for now, I'm using run program, and call chrome directly and pass the website that I wanted to access to achieve the same effect

**Comment by wcypierre** [comment]
> Can we please have a raw input option for 'open website' adding the `http://` yourself creates many weird issues if you try top open something that's not http.

I faced this issue too, for now, I'm using run program, and call chrome directly and pass the website that I wanted to access to achieve the same effect

**Comment by karl0ss** [comment]
Yeah i just run into this, opens https links with http://https://, bit annoying, will try you suggestion @wcypierre

**Comment by SuchByte** [comment]
Will be fixed in Macro Deck 2. Thank you!
