### ISSUE TITLE
Main website doesn't work

### ISSUE THREAD

**Issue by Adenser** [SuchByte/Macro-Deck#160]
Hello! I just wanted to report that the macrodeck.org site doesn't work at all. when you try to enter there is a DNS_PROBE_POSSIBLE error.
Also double-checked with DNS Checker
![image](https://user-images.githubusercontent.com/39248856/155365203-9ba101bb-9c69-4ad1-b08b-75190b85b36d.png)

**Comment by SuchByte** [comment]
This issue is known, it's because someone (me) forgot to renew the domain and now we have to wait until it's reactivated which can take a few days.
