### ISSUE TITLE
Can someone Spanish person help me?

### ISSUE THREAD

**Issue by Bartoliin9** [SuchByte/Macro-Deck#169]
El dia de hoy (2 de Marzo de 2022) descargué Macro Deck 2. La cosa iba bien, ya usé la versión anterior pero por unos problemas que tuve con mi antiguo móvil, dejé de usarla y ahora me encuentro con esta nueva. 

Bueno, pues durante la instalación me salieron un par de fallos, los cuales creo que son los que me impiden que me aparezcan los plugins en el apartado de ''Package Manager''. Lo e intentado solucionar, pero no e podido, y me gustaría que alguien me echara una mano.

Gracias 😄

**Comment by SuchByte** [comment]
Hubo algunos problemas técnicos con nuestro dominio. Esto debería funcionar ahora.
