### ISSUE TITLE
Macro Deck glow icon pack - (Animated) glow icon pack (WIP)

### ISSUE THREAD

**Issue by OvaKrdozo** [SuchByte/Macro-Deck#170]
** Name of the icon pack**

** Version **
The latest version of the icon pack

** Author of the icon pack **
The author name that will appear in the package manager

** Description of the icon pack **
What does the icon pack contain? A short description 20-30 words

** GitHub repository ** (Optional)
A link to the GitHub repository of the icon pack

**Comment by SuchByte** [comment]
@OvaKrdozo Hi, I really like your icon pack but since the new Extension Store it's not available anymore because many things changed. Are you interested in publish it again? If yes, please contact me on Discord. I'll guide you trough the steps. SuchByte#5461
