### ISSUE TITLE
Simple Blue icon pack update for v2.9.0

### ISSUE THREAD

**Issue by imohammedramadan** [SuchByte/Macro-Deck#190]
Repository for the icon pack
[Link](https://github.com/imohammedramadan/Macro-Deck-Simple-Blue-Icons)

**Comment by SuchByte** [comment]
The repository itself looks good but you need to do a few more steps to add it directly in the https://github.com/SuchByte/Macro-Deck-Extensions repo.

Make sure you have installed git on your computer and follow these steps:

1. Fork the https://github.com/SuchByte/Macro-Deck-Extensions repo
2. Create a folder on your computer for the repo and open a command promt in it
3. Clone the repo in this folder with `git clone https://github.com/SuchByte/Macro-Deck-Extensions`
4. Navigate to the cloned repo and add a submodule of your icon pack to the repo with `git submodule add https://github.com/imohammedramadan/Macro-Deck-Simple-Blue-Icons IconPacks/MidoMatrix.Simpleblue`
5. Commit the changes: `git commit -a -m "Added MidoMatrix.Simpleblue"`
6. Push the commit with `git push`
7. Create a pull request of your fork of the Macro-Deck-Extensions repo.
