### ISSUE TITLE
Locking of Keys

### ISSUE THREAD

**Issue by Termiplaygames** [SuchByte/Macro-Deck#194]
**Describe the bug**
I have discovered today that after a PC restart all keys that are assigned in the macro deck are "blocked". 

It becomes impossible to use the keys until Macro Deck is deactivated or terminated.

**To Reproduce**
![image](https://user-images.githubusercontent.com/68549014/159311297-f88c6497-41fb-420f-afbc-b3c6b8a1b112.png)
every butten wich is settet up on the bottom left site will be blocked

**Comment by SuchByte** [comment]
This is not a bug. The hotkeys you assign there are for executing the button's actions. If you want to simulate the key presses with a press of the button, you need the Windows Utils plugin with the "Hotkey" action.

**Comment by Termiplaygames** [comment]
so when i set the hotkey, it is normal that im not able to use the buttons on my keyboard anymore?
