### ISSUE TITLE
Macro Deck crashes when connecting to twitter

### ISSUE THREAD

**Issue by StrawberryMahjong** [SuchByte/Macro-Deck#2]
Title says it all, I tried to connect my twitter to Macro Deck and it just froze before closing. Is there a fix for this?

**Comment by Ushantilp** [comment]
I Love this Program, but i have the Same Issue, i know SuchByte has no time, but I hope he can fix this soon. That's one of the main features I need

**Comment by SuchByte** [comment]
Will be fixed in Macro Deck 2!
