### ISSUE TITLE
Application does not run (windows 10)

### ISSUE THREAD

**Issue by juniorafael** [SuchByte/Macro-Deck#203]
Hi!

I installed the application but it doesn't run, I already installed ".NET Desktop Runtime 3.1" and nothing, it doesn't show any kind of error.

**Comment by SuchByte** [comment]
Hi, please upload the latest log file located in `%Appdata%\Macro Deck\logs`

**Comment by juniorafael** [comment]
10:22:27 [Macro Deck] [Info] >> 
==========================================
10:22:27 [Macro Deck] [Info] >> Starting Macro Deck version 2.10.0.220921800
10:22:27 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
10:22:27 [Macro Deck] [Info] >> OS: Windows 10 build 19044 64 bit
10:22:27 [Macro Deck] [Info] >> Network interfaces: 
Ethernet - 192.168.10.23
Loopback Pseudo-Interface 1 - 127.0.0.1
10:22:27 [Macro Deck] [Info] >> Loading language files...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
10:22:27 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
10:22:27 [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: System.BadImageFormatException: Could not load file or assembly 'CefSharp.Core.Runtime, Version=99.2.120.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. Foi feita uma tentativa de se carregar um programa com um formato incorreto.
File name: 'CefSharp.Core.Runtime, Version=99.2.120.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at CefSharp.CefSettingsBase..ctor()
   at SuchByte.MacroDeck.MacroDeck.Main(String[] args) in D:\Macro-Deck\Macro Deck 2\MacroDeck.cs:line 365

**Comment by SuchByte** [comment]
Please try to install this file: https://macrodeck.org/files/test/macro-deck-2.10.0-beta.exe

Tell me if this works because I can't reproduce this issue and for most other users it works too.

**Comment by juniorafael** [comment]
22:49:30 [Macro Deck] [Info] >> 
==========================================
22:49:31 [Macro Deck] [Info] >> Starting Macro Deck version 2.10.0.220951849 with parameters: --show
22:49:31 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
22:49:31 [Macro Deck] [Info] >> OS: Windows 10 build 19044 64 bit
22:49:31 [Macro Deck] [Info] >> Network interfaces: 
Ethernet - 192.168.10.23
Loopback Pseudo-Interface 1 - 127.0.0.1
22:49:31 [Macro Deck] [Info] >> Loading language files...
22:49:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
22:49:32 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
22:49:32 [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: System.BadImageFormatException: Could not load file or assembly 'CefSharp.Core.Runtime, Version=99.2.120.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. Foi feita uma tentativa de se carregar um programa com um formato incorreto.
File name: 'CefSharp.Core.Runtime, Version=99.2.120.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at CefSharp.CefSettingsBase..ctor()
   at SuchByte.MacroDeck.MacroDeck.Main(String[] args) in D:\Macro-Deck\Macro Deck 2\MacroDeck.cs:line 365

**Comment by SuchByte** [comment]
I finally found the issue. This can be due to the missing Microsoft Visual C++ Redistributable on your computer. Try to install this: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by SuchByte** [comment]
It's now directly included in the installer. Just download the latest version on the website (https://macrodeck.org/download) and install it. After that it will work!

**Comment by juniorafael** [comment]
actually, i cleaned my computer recently and it must have been missing some components. thanks for helping friend

**Comment by juniorafael** [comment]
actually, i cleaned my computer recently and it must have been missing some components. thanks for helping friend

**Comment by juniorafael** [comment]
It worked, now it works
