### ISSUE TITLE
Misty - Icon Pack Submission

### ISSUE THREAD

**Issue by whosthispuppy** [SuchByte/Macro-Deck#219]
**Name of the icon pack**
Misty

**Version**
1.0.0

**Author of the icon pack**
PUPPY MEDIA

**Description of the icon pack**
Bright Icons in a Modern and Sleek Design with Glossy elements to lighten up your Deck.

**Github Repository**
https://github.com/whosthispuppy/misty

**Icon Pack File**
https://github.com/whosthispuppy/misty/blob/main/rel/Misty.macroDeckIconPack

**Comment by SuchByte** [comment]
To submit icon packs (Extensions), please follow these steps: https://github.com/SuchByte/Macro-Deck-Extensions/blob/main/IconPacks/README.md

If you need help, please join the Discord server.
