### ISSUE TITLE
[BUG] Webrequest and Open website actions prepends "http://" to any URL

### ISSUE THREAD

**Issue by theS1LV3R** [SuchByte/Macro-Deck#4]
If I select either the `Webrequest` or `Open Website` actions it automatically prepends `http://` to the URL. If I for example want to use the `Webrequest` action to open a steam game (Which uses `steam://ruungameid/gameid` URLs), they will not work.

GIF to show what i mean:
![Example GIF](https://user-images.githubusercontent.com/32072697/70647294-ebf2c380-1c48-11ea-9cb4-b8fb7af814ce.gif)

**Comment by ent3r** [comment]
@SuchByte

**Comment by SuchByte** [comment]
Use the "Run program"-macro to open Steam games.

**Comment by ent3r** [comment]
Using "Run Program" launches the executable, but not the steam game handler. You have tu use the "steam://" URLs

**Comment by samahub** [comment]
Yeah, I have the same issue dealing with https URLs, which btw should be predefined option if any nowadays.

**Comment by samahub** [comment]
Any chance you open the code for community support?

**Comment by SuchByte** [comment]
Will be fixed in Macro Deck 2. Also will be a separate plugin which will be open-source!

**Comment by ElEmFurt** [comment]
So in Macro Deck 2, I am not seeing the system menu itself, so how does one add a web request? Do suggest.
