### ISSUE TITLE
Obs Plugin volume bug 

### ISSUE THREAD

**Issue by AshbossGaming** [SuchByte/Macro-Deck#56]
the volume scale on the obs plugin is wrong i can only move between -3dB and 7dB whereas obs scale is from 0dB to -100dB
![image](https://user-images.githubusercontent.com/93836965/140618967-cb3958a9-270a-42d6-a69e-309f83b369da.png)

also if its at -100dB i can go up to 0dB but can't go back down i get stuck at -3dB.

**Comment by SuchByte** [comment]
I close it because you also opened it in the repository of the plugin.
https://github.com/SuchByte/Macro-Deck-OBS-WebSocket-Plugin/issues/1
