### ISSUE TITLE
Run commandline commands in the background

### ISSUE THREAD

**Issue by zedalert** [SuchByte/Macro-Deck#67]
Currently commandline commands and applications (even if they support silent mode) are started in the visible window, taking focus onto themself and interrupting fullscreen applications.

It would be great if they would run completely silent in the background.
And maybe someone also interested in separate options to run PowerShell and WSL scripts, not only regular command line.

**Comment by SuchByte** [comment]
I close this issue here because it's something for the Windows Utils repository.

Link to the issue: https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin/issues/3
