### ISSUE TITLE
Icons not always rendering correctly

### ISSUE THREAD

**Issue by PhoenixWyllow** [SuchByte/Macro-Deck#68]
**Describe the bug**
Icons behave in strange ways with low carner radius setting. A simple box icon will render seemingly out of bounds on radius 0, 1, or 2 and may begin cutting at radius lower than 5. 
At higher corner radius values, the icons may even appear not centered.

**To Reproduce**
1. Download this example icon: [Frames at 512x512](https://user-images.githubusercontent.com/54237626/141662126-a38a8d2b-12c2-424f-b07a-ff1cc1ee3c30.png)
2. Add to a new icon pack at original size.
3. Create a button with this icon.
4. Change corner radius to 10.
5. Repeat step 4 for radius = 5,4,3,2,1,0
6. Since the example icon has lines with a corner radius of 30, repeat step 4 with radius = 40 to see the uncentered effect. (truncation is expected, but even at all 4 corners)

**Expected behavior**
1. Icons should be rendered centered on buttons.
2. Icons should always render within bounds of the button, not be truncated at low corner radius values.

**Screenshots**
The attached example is a merge of these 3 I tested:
![image](https://user-images.githubusercontent.com/54237626/141662284-9fe83610-366f-40fe-8f19-8d015507135c.png)
![image](https://user-images.githubusercontent.com/54237626/141662287-d78000b0-03cf-4d59-a884-0873b1b2a931.png)
![image](https://user-images.githubusercontent.com/54237626/141662464-4217da90-c95f-42a0-8b64-f473047d6851.png)

**Additional context**
Using Macro Deck 2.3.2-dev

**Comment by PhoenixWyllow** [comment]
This issue also seems to appear on the "built-in" icon pack, though possibly more evident:
(with button background)
![image](https://user-images.githubusercontent.com/54237626/141662529-f12fa456-bc4f-48a2-b3ea-d1a653aeb094.png)
(without background)
![image](https://user-images.githubusercontent.com/54237626/141662535-8a900dc7-c1a2-4e6b-b0ea-48d12327d49d.png)

Could this be also partly be due to a border element on the button?

**Comment by PhoenixWyllow** [comment]
Also, border thickness seems to change.
The images in the previous comment were taken with radius 0.
This is with radius 10:
![image](https://user-images.githubusercontent.com/54237626/141662721-f49cdd6a-4d25-4b71-b390-ec8085bc746e.png)

**Comment by SuchByte** [comment]
Will be fixed in the next version
