### ISSUE TITLE
New Action: Text String Input

### ISSUE THREAD

**Issue by NightB1ade** [SuchByte/Macro-Deck#72]
**Is your feature request related to a problem? Please describe.**
I would like to be able to be able to express a complete text string using an action (in contrast to the hotkeys action).  For example, the ability to add a string representing my email "example@example.com" or a coding phrase "&lt;p>" and drop that on a press of a button action.

**Describe the solution you'd like**
A new action that has a text box for input, and when running the action, the text string to appear where the window/caret currently has focus.

**Describe alternatives you've considered**
None considered as of this stage.

**Additional context**
Additionally, would like to be able to use variables in inputs.  For example, the ability to use the action to output today's date.

**Comment by SuchByte** [comment]
I added this feature to the Windows Utils plugin version 1.4.0
