### ISSUE TITLE
New Action: Switch Windows

### ISSUE THREAD

**Issue by NightB1ade** [SuchByte/Macro-Deck#73]
**Is your feature request related to a problem? Please describe.**
I would like to switch windows using an in-built action in MacroDeck2

**Describe the solution you'd like**
An option in the Actions list to switch windows.  It should be able to identify the window required full/partial string matches.

**Describe alternatives you've considered**
I have considered using imprecise window switching by using Win+number, or alt-tab, or Win-tab.  Doesn't quite work as well as precise window switching that I am envisioning.

**Additional context**
Nothing of note.

**Comment by SuchByte** [comment]
Moved it to the issues page of the Windows Utils plugin.

https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin/issues/7
