### ISSUE TITLE
Key Macro: Improvements (Key-Down, Key-Up)

### ISSUE THREAD

**Issue by NightB1ade** [SuchByte/Macro-Deck#74]
**Is your feature request related to a problem? Please describe.**
I would like to define the key macros to a finer degree, to be able to specify key-down, and key-ups as required.  Thus, this allows the ability to do key-held shortcuts, for example alt-tabbing until the required window or Win+number to get to the second window for switching.

**Describe the solution you'd like**
To be able to define key-downs and key-ups separately as part of the key macros.

**Describe alternatives you've considered**
A bonus would be able to record the macro from the keyboard instead of manually defining it.

**Additional context**
Added a screenshot of something equivalent that was constructed using Corsair's iCue software.

![unknown](https://user-images.githubusercontent.com/18259801/142441960-5eb049fc-03dd-4987-bf31-880bef125909.png)

**Comment by SuchByte** [comment]
Moved it to the issues page of the Windows Utils plugin.

https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin/issues/6
