### ISSUE TITLE
Can't set variable

### ISSUE THREAD

**Issue by Daenara** [SuchByte/Macro-Deck#82]
**Describe the bug**
I just found this and it looks promising, but I haven't figured out how to actually use variables yet. It might be me being stupid or I found an actual bug, but when I try to set a variable on button press I can't select which variable to set because the drop down menu is empty. I created a variable that I hoped I would be able to save my current obs scene to, but so far I haven't even been able to save anything.

**To Reproduce**

**Expected behavior**
I would expect there to be a list of variables to select.

**Screenshots**
![empty_variables](https://user-images.githubusercontent.com/3619315/142912476-024ad4a1-278e-497f-8c21-3d131c940732.png)

**Additional context**
Because I am not sure if this is a bug or me not knowing what I am doing I wanted to ask on the discord but for some reason I can't post anything on there. I get an error where Clyde (the discord bot) tells me I am not allowed to send a private message to this user which seems kinda strange since I am trying to write something in a discord server. I tried 3 different channels and, since my message was kinda long, a shorter one and nothing changed. Not sure if discord has issues today or if it is something with the server.

**Comment by zedalert** [comment]
It's not a bug. A drop down list will not show you variables until you select the action below. Because action depends on variable type, i.e. you can't count up boolean variables.

I think a better solution would be graying the checkboxes depending on what variable you have chosen, also variables in the variable drop down list should be visible all the time.

**Comment by NightB1ade** [comment]
Seconded the above.  (too slow typing for me!)

I think flow of the UI needs changes.  Either the above, or even switching around the interface so you choose the radio button first before variable.  (My preference would be what @zedalert has suggested though!)

**Comment by SuchByte** [comment]
As @zedalert said, it's not a bug but I agree that the ui is not very intuitive. I'll change this with one of the next updates.

**Comment by Daenara** [comment]
Okay, thanks for that. So I at least can see my own variable now. I don't see any obs plugin variables but I am not sure if I should see them. I had hoped for some way to save the active scene inside a variable when switching to my brb scene and being able to restore it afterwards but I don't think the variable system can do that yet.
