### ISSUE TITLE
Variables: Calculations

### ISSUE THREAD

**Issue by NightB1ade** [SuchByte/Macro-Deck#86]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The ability to conduct calculations on variables (over and above the current options).  For example, multiplications, divisions, other more complex formulae.

**Describe alternatives you've considered**
None considered

**Additional context**
Not applicable

**Comment by SuchByte** [comment]
Will be added in 2.5.0-dev
