### ISSUE TITLE
Variable values are not expanded after changing button state action

### ISSUE THREAD

**Issue by gis-dur** [SuchByte/Macro-Deck#88]
**Describe the bug**
On the button's appearance, variables are not expanded when button state changes to 'On'
It just displays the variable name, like '{Time}', instead of displaying the real time.
The display immediately fixes correctly when you edit the label definition.
On Windows 11, using Macro Deck 2.4.1-dev

**To Reproduce**
1. Go to the main screen
2. Double Click any button
3. Click '+' on the 'On press' tab and select 'Action'
4. Select 'This action button -> Toggle button state' and click OK
Note: Same thing happens when selecting 'This action button -> Set button state to on'
5. On the Appearance, select Button state Off, and Input '{Date}'
6. On the Appearance, select Button state On, Input '{Time}'
7. Click 'Save' and 'OK' (or just 'OK')
8. On the Android Client, press the button

The label on the button says '{Time}'.

9. Double click the button on the Server application again
10. On the Appearance, select Button state On

The label on the button still says '{Time}'.

11. Set the cursor after '{Time}' and press the space key

The label now shows the real time correctly (plus a white space).

12. Click 'Save' and 'OK' (or just 'OK')

The label on the button shows '{Time} '.

**Expected behavior**
The button always shows the real time.
On both the server/client applications.

**Screenshots**
After No.1
![1](https://user-images.githubusercontent.com/94933049/143690213-16778ead-f90d-4c8a-abbb-96988334e722.png)

After No.2
![2](https://user-images.githubusercontent.com/94933049/143690222-c09ed580-da16-4fd5-98eb-c44f61a94de0.png)

After No.3
![3](https://user-images.githubusercontent.com/94933049/143690226-6c6d9085-d753-40b0-8d74-2e17a6d12073.png)

After No.4
![4](https://user-images.githubusercontent.com/94933049/143690231-01af984c-b351-4029-9c12-233c34e1b73b.png)

After No.5
![5](https://user-images.githubusercontent.com/94933049/143690240-47f0ad47-c6e0-446a-9948-198c40313699.png)

After No.6
![6](https://user-images.githubusercontent.com/94933049/143690244-eac0b704-df05-49d3-acf6-9e0d8fe41d4b.png)

After No.7
![7](https://user-images.githubusercontent.com/94933049/143690248-bc541d33-327a-4143-8e89-579884184eda.png)

After No.8
![8](https://user-images.githubusercontent.com/94933049/143690255-a1936e71-c6d4-4d8d-81ef-2a366f54c73c.png)

After No.9
![9](https://user-images.githubusercontent.com/94933049/143690260-5542cab9-dc33-4fae-a094-15247b10e1c3.png)

After No.10
![10](https://user-images.githubusercontent.com/94933049/143690261-fbf9376a-699d-49ad-b185-2e37ad133998.png)

After No.11
![11](https://user-images.githubusercontent.com/94933049/143690267-555a76ae-09c6-4e07-b61c-6c4d2fa81df5.png)

After No.12
![12](https://user-images.githubusercontent.com/94933049/143690271-ee65c75a-0f9e-4fc8-82d3-d2f52d6117fa.png)

**Additional context**
None.

**Comment by SuchByte** [comment]
Cannot replicate the bug in 2.5.0-dev. Maybe it's fixed because I changed the entire variable system.

**Comment by gis-dur** [comment]
Confirmed.
Thank you for the fix!!
