### ISSUE TITLE
focused_application sometimes sticks to 'explorer' after switching windows with Alt+Tab

### ISSUE THREAD

**Issue by gis-dur** [SuchByte/Macro-Deck#89]
**Describe the bug**
When you switch windows by pressing Alt+Tab key, the focused_application value sometimes sticks to 'explorer'.
Switching windows by mouse click is working fine, only happens on key strokes.
On Windows 11, using Macro Deck 2.5.0-dev

**To Reproduce**
Not 100% reproducing, but at a high rate:

1. Go to the main screen
2. Double Click any button
3. On the Appearance, set the Label to '{focused_application}'
4. Click 'Save' and 'OK' (or just 'OK')
5. Open a Microsoft Edge window
6. Open the Macro Deck server application window
7. Set both window sizes small so that you can click them one at a time
8. Now first click the Microsoft Edge window

In the client, the button label becomes 'msedge' (Correct).

9. Next, click the Macro Deck server application window

In the client, the button label becomes 'Macro Deck 2' (Correct).

10. Press the Alt+Tab key and release only the Tab key (keep holding the Alt key down)

On the Windows screen, the _Task Switcher_ is shown.
On the Client Application, the button label becomes 'explorer' (Correct).

11. Release the Alt key, so that you've selected the Edge window on the _Task Switcher_.

On the Windows screen, the Edge window is focused.
On the Client Application, the button label is stuck to 'explorer' (INCORRECT) at high rate, but not always.

12. Press Alt+Tab a few more times, and see the Client Application's button label for each try

If the issue is once reproduced, then the behavior seems to stick like below (but not always):
When the Macro Deck window is focused by Alt+Tab, the label becomes 'Macro Deck 2' (Correct).
When the Edge window is focused by Alt+Tab, the label becomes 'explorer' (INCORRECT).

**Expected behavior**
Whenever the window is focused by Alt+Tab (after releasing the Alt key), the label becomes the name of the focused window's executable, same as when focused by mouse click.

**Screenshots**
None.

**Additional context**
One curious thing is, if you click the windows the other way around (as below), then reproducibility is significantly reduced low.
8. First, click the Macro Deck server window
9. Next, click the Microsoft Edge window
10. Press the Alt+Tab key and release only the Tab key (keep holding the Alt key down)
11. Release the Alt key, so that you've selected the Macro Deck window on the _Task Switcher_.

This time, it is likely to be correct; when you release the Alt key in Step 11, the label changes from 'explorer' to 'Macro Deck 2'. (but not always)
I assume there is an 'on focus initialization' event on the Macro Deck server application that updates the focused_application variable correctly, while on the other hand, it loses opportunity to update the variable if the focused window is not Macro Deck 2.

**Comment by SuchByte** [comment]
I could verify this big. I made the event now synchrounous and I think this fixed it. You can try it again with the next update.

**Comment by gis-dur** [comment]
Thank you for fixing this.
It is now MUCH LESS likely to happen, but it still happens in rare cases when I use Alt+Tab to switch between two or more windows very rapidly.
I think it is difficult to make further improvements (I'm not sure if there even is a solution), so I would like to mark this issue solved for now.
Thanks again.

**Comment by hellishvictor** [comment]
I thought that only happen using the Stream Deck client, still waiting for elgato to fix this.
