### ISSUE TITLE
Copy-Pasting the same button multiple times doesn't work

### ISSUE THREAD

**Issue by gis-dur** [SuchByte/Macro-Deck#90]
**Describe the bug**
After copying a button, if you paste it to two or more different buttons, only the last one is valid.
The last button seems to have duplicate instances, since after reproduction, you can delete it more than once.
On Windows 11, using Macro Deck 2.5.0-dev

**To Reproduce**
1. Go to the main screen
2. Double Click any button
3. On the Appearance, set the Label to anything, for instance 'TEST'
4. Click 'Save' and 'OK' (or just 'OK')
5. Right click on the button you just made, and select Copy
6. Right click on another empty button, and select Paste

There are two buttons labeled 'TEST'. (Correct)

7. Right click on another empty button, and select Paste

The button you pasted in Step 6 disappears, and only buttons made by Step 2-4 and 7 remains. (NOT EXPECTED)

8. Right click on another empty button, and select Paste (and so on...)

The button you pasted in Step 6 and 7 disappears, and only buttons made by Step 2-4 and 8 remains. (NOT EXPECTED)
Just paste it any times you want in a row.

9. Right click on the last button you pasted (in step 8) and select Delete

The button remains (looks like it's not deleted).
If you right click on the same button, you are able select Delete it again.

**Expected behavior**
When you paste a button, Every other button remains and doesn't disappear; all buttons are independent. (step 7 and 8)
Every button can be deleted only once. (step 9)

**Screenshots**
After step 4
Note:
I've added an additional variable 'test_int',
added to the label like 'TEST {test_int}',
and created an On Press Activity which counts up 'test_int',
so that I can monitor what happens when I click the button.
Reproduces 100% with or without the additional settings.
![b2_4](https://user-images.githubusercontent.com/94933049/143763196-e98a06b7-4bc4-45df-b2a3-a3b3c6ae479c.png)

After step 6
![b2_6](https://user-images.githubusercontent.com/94933049/143763200-628d4504-1da5-4bc9-8169-6b3a1048326a.png)

After step 7
![b2_7](https://user-images.githubusercontent.com/94933049/143763207-94eddf56-5fcd-49d9-b908-bcef1392baec.png)

After step 8
![b2_8](https://user-images.githubusercontent.com/94933049/143763210-b5a6c2ea-a6ed-4d3a-aef3-1418b7c33fe5.png)

When I press the last button (created at step 8) on my android client, it counts up only once, so the Count Up Action is executed only once.
![b2_8-2](https://user-images.githubusercontent.com/94933049/143763214-24f517af-375d-4d75-bdda-53488262171d.png)

After step 9
![b2_9](https://user-images.githubusercontent.com/94933049/143763215-23bc9b93-6e7c-49ad-8ee2-60567637b5f1.png)

Tried deleting the button again, but it still remains.
![b2_9-2](https://user-images.githubusercontent.com/94933049/143763218-1d3b90c2-7929-4c5d-8866-66a1e2e6bb1d.png)

At the third time, the button is finally really deleted.
![b2_9-3](https://user-images.githubusercontent.com/94933049/143763221-58f8eaba-ed5f-472d-8f8a-970084068433.png)

**Additional context**
I suspect that there are multiple instances in the same button (specifically 3 in the example procedure, each pasted in steps 6, 7, and 8),
so you can Delete the button multiple times (specifically 3 times in the example procedure).
Maybe some problem using pointers, or references, or something like that? Not sure.

**Comment by gis-dur** [comment]
Additional Information.
If you paste the same button multiple times to different Macro Deck Folders, the results are more complicated.

1. Copy a button in a Macro Deck Folder (1)
2. Switch to a different Macro Deck Folder (2)
3. Paste it to a button in the same position
4. Switch to a different Macro Deck Folder (3)
5. Paste it to a button in the same position
6. Switch back to the Macro Deck Folder (2) (the one used in step 2)
7. Move the button to a different place by dragging it
8. Switch back to the Macro Deck Folder (3) (the one used in step 4)

The button in Macro Deck Folder (3) also moves to the position specified in step 7.
Expecting it not to move.

If the place where you drag in the button in Macro Deck Folder (2) is empty and in Macro Deck Folder (3) is pre-defined, by step 7 the button seems to be some weird state.
I suppose both button instances become at the same place, and whenever the label refreshes (for instance by counting up a variable in the label), it shows up.

**Comment by SuchByte** [comment]
Macro Deck created a copy of the instance of the action button when copy. Now it creates a copy when the button is pasted. This should fix it.

**Comment by gis-dur** [comment]
Confirmed.
Thank you for the fix!!
