### ISSUE TITLE
Variables: Calculations in the 'Change variable value' Action

### ISSUE THREAD

**Issue by gis-dur** [SuchByte/Macro-Deck#92]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's just for fun (at least for now).

For instance, suppose there is a button showing CALORIES I've ate today.
And there is this nice yummy CHOCOLATE CHIP COOKIE button which raises like 22kcal per tap on the button,
while there is another big HAMBURGER button which raises like 525kcal per tap on the button.
Or maybe a delicious PIZZA button which raises like, uh... 1600kcal? and at the same time, shows the pizza_menu.pdf on the computer's screen when tapped.

Now, if it is only dealing with COOKIES, it's simple.
You set the 'num_cookie' varaible count up on button action, and show `'{num_cookie*22} kcal'` on the label.
Works GREAT! (Thanks to #86 Implemented in 2.5.0-dev)
Last thing to do is to add an Event Trigger 'Variable changed -> date' and reset 'num_cookie' to zero when the date changes.

But If you have more than one menu, the formula will be complicated, like this:
`'{num_cookie*22 + num_hamburger*525 + num_pizza*1600} kcal'`
Adding menus will make the formula longer and longer, hard to maintain.
And the reset event will be frustrating, too; you will have to reset all counters of each menu.

**Describe the solution you'd like**
It would be nice to have functionality to set calculated result values to a variable.
So you only need to define one variable, 'calories_today', show it in a label, and the button actions will be like:

- COOKIE button : calories_today -> Set -> {calories_today+22}
- HAMBURGER button : calories_today -> Set -> {calories_today+525}
- PIZZA button : calories_today -> Set -> {calories_today+1600}

and the reset event when date changes will be like:

- calories_today -> Set -> 0

You can add any other menus you want, only add the button, formulas are simple and no frustration.

**Describe alternatives you've considered**
Maybe functionality to pass variable values to a command line parameter could do the same.
Calculate in the command, and save output to a variable.
That will be a request for the Windows Utils plugin.

I believe there is no alternative, but sorry if I am missing any feature and if there is a workaround.

**Additional context**
None.

**Comment by SuchByte** [comment]
Added to version 2.5.1-dev

**Comment by gis-dur** [comment]
Thank you for the Implementation.
It is working PERFECTLY !!
Now I can keep track of my calorie intake :)
