### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by gis-dur** [SuchByte/Macro-Deck#93]
My browser shows that the SSL Certificate for "Let's Encrypt / macrodeck.org" has expired.
Begin: Wed, 01 Sep 2021 15:22:54 GMT
End: Tue, 30 Nov 2021 15:22:53 GMT

In addition, I am not sure if it's the same reason, but the Package manager now shows no plugin on the Online tab.

[Edit]
I cannot update Macro Deck neither. Tested by the steps below:
1. Uninstall 2.5.1-dev
2. Re-Install 2.3.3-beta
3. Start Macro Deck and open Settings -> Updates
4. Press 'Check for updates now' button

Nothing happens.

**Comment by SuchByte** [comment]
Yes, I totally forgot to renew it. It should work now again.

**Comment by gis-dur** [comment]
Thank you. It is now working perfectly.

**Comment by gaibbbstr** [comment]
same renew sssl
