### ISSUE TITLE
wifi change while is running = delete deck info

### ISSUE THREAD

**Issue by OldisekT** [SuchByte/Macro-Deck#94]
i had macro deck running and my wifi crashed so i change my wifi to neighbors wifi and my macro deck data all butons were gone.
but all plugins and variables are still in the app
![image](https://user-images.githubusercontent.com/88963084/144227829-73d71e31-0ff5-4530-9185-ccabfe421d2e.png)

**Comment by caosbinario** [comment]
Maybe you have wrongly configured the network adapter.

Try to change this

![image](https://user-images.githubusercontent.com/32986414/146816018-39c09e8c-71a3-48f9-999b-4246d148a124.png)
