### ISSUE TITLE
I Cant create variables

### ISSUE THREAD

**Issue by caosbinario** [SuchByte/Macro-Deck#98]
**Describe the bug**
Any variable I try to create throws me an error

**To Reproduce**
1. Go to 'Global variables'
2. Click on 'Create variable'
3. Fill the form.

**Expected behavior**
I hope you can create a variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/32986414/146679095-0450f187-734f-4798-a2d1-050c6302d97b.png)

**Additional context**
Something abnormal that I see is that the error begins with disk D:/..., and I don't have disk D:/ as you can see.

**Comment by SuchByte** [comment]
It would be useful if you paste the error message here because I can't replicate the bug.

> Something abnormal that I see is that the error begins with disk D:/..., and I don't have disk D:/ as you can see.
That's nothing abnormal, this is the path of the compiled class which is on my D: drive, this has nothing to do with this issue and is normal.

**Comment by caosbinario** [comment]
Sure, The error message:

> 
> Macro Deck version: 2.6.2.213531724
> Windows version: Windows 10 Education 64 bit
> 
> Object reference not set to an instance of an object.
> 
>    at SuchByte.MacroDeck.Variables.Plugin.VariableChangedEvent.<Trigger>b__9_1(EventListener x) in D:\Macro-Deck\Macro Deck 2\Variables\Plugin\VariablesPlugin.cs:line 84
>    at System.Collections.Generic.List`1.Find(Predicate`1 match)
>    at SuchByte.MacroDeck.Variables.Plugin.VariableChangedEvent.<Trigger>b__9_0(ActionButton actionButton) in D:\Macro-Deck\Macro Deck 2\Variables\Plugin\VariablesPlugin.cs:line 84
>    at System.Collections.Generic.List`1.FindAll(Predicate`1 match)
>    at SuchByte.MacroDeck.Variables.Plugin.VariableChangedEvent.Trigger(Object sender) in D:\Macro-Deck\Macro Deck 2\Variables\Plugin\VariablesPlugin.cs:line 78
>    at SuchByte.MacroDeck.Variables.VariableManager.RefreshVariable(Variable variable) in D:\Macro-Deck\Macro Deck 2\Variables\VariableManager.cs:line 37
>    at SuchByte.MacroDeck.GUI.Dialogs.VariableDialog.BtnOk_Click(Object sender, EventArgs e) in D:\Macro-Deck\Macro Deck 2\GUI\Dialogs\VariableDialog.cs:line 94
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by caosbinario** [comment]
See this video: https://youtu.be/t7QoxCd5IGQ  
I hope this helps you

**Comment by SuchByte** [comment]
Can you please contact me on Discord? ( SuchByte#5461 ) Because no matter what I try, I can't figure out what causes this crash on your installation.

**Comment by caosbinario** [comment]
I sent the friend request
![image](https://user-images.githubusercontent.com/32986414/146957662-ae77a334-1793-4331-9b72-1723506d814b.png)

**Comment by SuchByte** [comment]
Somehow I didn't received it. I think it would be easier if you join the Macro Deck Discord server ( https://discord.gg/yr7TRaXum8 ) and then create a new support ticket or send me a private message.

**Comment by caosbinario** [comment]
I found something.
From other user in my pc, I can create vars, but from my user dont.
Additional, if I past the "variables" file, It works.
![image](https://user-images.githubusercontent.com/32986414/146995267-87ea171d-ee52-42a3-897e-549412cec72d.png)

But, When I try to create another var, Its fails.

**Comment by SuchByte** [comment]
Will be fixed in the next version.
